version: '3.7'

services:
  server-bootstrap:
    image: consul:1.7.3
    container_name: consul_master
    restart: always
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8500:8500
      - 53:8600/udp 
    volumes:
      - ./consul/data:/consul/data
      - ./consul/config/:/consul/config/
    command: "agent -config-dir=/consul/config/"